### PR TITLE
Fixed celery.Events.state.State.tasks_by_time for celery 3.1

### PR DESCRIPTION
**Pull request by amirrpp**
`tasks_by_time` method for celery 3.1 don't have `reverse` parameter

### CODE REVIEW

**Comment by rsalmei** [comment]
Hey @amirrpp,

Thank you very much for your PR, but unfortunately it includes several new lines which are not covered with tests.
I've inspected the celery code, and realized you grabbed that code directly from celery 4, which is ok, but with that code in here, it would have to be tested here.

I'm going to think about how to fix this, but unfortunately this is not the way.
Would you please open an issue with the stacktrace exception?

**Comment by rsalmei** [comment]
Wow, I got it! I know how to fix that!
Looking at the celery 3 code, I saw that the reverse **is already there**! They just made it optional in celery 4!! Look:

```python
    def tasks_by_time(self, limit=None):
        """Generator giving tasks ordered by time,
        in ``(uuid, Task)`` tuples."""
        seen = set()
        for evtup in islice(reversed(self._taskheap), 0, limit):  <<<<<<<<<<<<<<
            task = evtup[3]()
            if task is not None:
                uuid = task.uuid
                if uuid not in seen:
                    yield uuid, task
                    seen.add(uuid)
```

So, the best fix for this problem would be to just remove the `reverse` argument from there!

Well, I'm going to close this PR and fix that, if you could open that issue just to have a history, I could link with it.
Thank you again for bringing up that problem.

**Comment by rsalmei** [comment]
Hey @amirrpp, have you had a chance to review if the new Clearly 0.8 fixes this problem?
Could you please report in the issue #48 ?

**Comment by amirrpp** [comment]
Hey, thanks for your answer. I can't already check it because I am updated celery to 4.4.

**Pull request closed without merging**
